#name: CI

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

#jobs:
#  test:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3

#      - name: Setup Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: 18

#      - name: Install dependencies
#        run: npm install

      # Si en el futuro se añade tests de UI, activar esta línea:
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps

#      - name: Run Playwright API tests
#        run: npx playwright test tests-api --reporter=html

#      - name: Upload Playwright Report
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: playwright-report
#          path: playwright-report/
